# Generated by Django 6.0.7 on 2026-07-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='income',
            field=models.BooleanField(default=False),
        ),
    ]
