# Generated by Django 6.0.7 on 2026-07-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catagory_income'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='catagory',
            new_name='category',
        ),
    ]
